sanni/cartreader

- Cart_Reader/Cart_Reader.ino
- Cart_Reader/N64.ino
- Cart_Reader/NP.ino
- Cart_Reader/SNS.ino
> Support for SDD1 and warning fixes

- Cart_Reader/SNES.ino
snes_speedup: optimized SNES dumping performance by reducing ROM read delays and increasing the SD card buffer from 512B to 1024kB; dumps a 32Mbit cart in 14 seconds now, 10 of which are for the SD card access :)
> faster snes dumping

- Cart_Reader/Cart_Reader.ino
- Cart_Reader/N64.ino
- Cart_Reader/PCE.ino
- Cart_Reader/SNES.ino
Included the progress bar in the N64 and SNES modules; some OLED formatting; reverting the Arduino reset to basically jmp 0 again (due to issues with some Mega2560 bootloaders probably, my module would sometimes just hang)
> progress_bar

- Cart_Reader/MD.ino
speedup and progress bar for MD module; display the ROM stored CRC in overview
I'd also like to add CRC checking but the algorithm descriptions I found are vague.
It should be similar to SNES though.
> speedup and progress bar for MD module

- Cart_Reader/Cart_Reader.ino
> various: forward declaration for "T" type used in EEPROM functions

- Cart_Reader/Cart_Reader.ino
- Cart_Reader/GB.ino
- Cart_Reader/GBSmart.ino
Add support for EMS GB Smart 32M flash cart.
Now only supports cart with two LH28F016SUT flash memory.
> Add support for EMS GB Smart 32M flash cart

- Cart_Reader/FLASH.ino
Add support for MBM29F800BA/AM29F800BB and LH28F016SUT.
> Add support for MBM29F800BA/AM29F800BB and LH28F016SUT

- Cart_Reader/GBA.ino
> Add support for Intel PC28F256M29

- Cart_Reader/WS.ino
Also fixed "Mobile Suit Gundam Vol.2 - JABURO" could not dump properly.
> Add more developerId

- Cart_Reader/snes_clk.cpp
- Cart_Reader/snes_clk.h
Updating this to match the rest of the exFAT changes.
> Updated snes_clk for exFAT changes

- Cart_Reader/NGP.ino
Comments added
Some "nice-to-have" added
> NGP.ino Update

- Cart_Reader/MD.ino
This game allows players to insert a second cartridge. (called Lock-on Technology)
At this time, the memory map is as follows.
Default mode
>   0x000000-0x200000  Sonic & Knuckles rom
>   0x200000-0x400000  Lock-on side rom
Sonic2 mode (When Sonic2 is detected, write 1 to $ 00A130F1 to switch)
>   0x000000-0x200000  Sonic & Knuckles rom
>   0x200000-0x300000  Lock-on side rom
>   0x300000-0x340000  Knuckles the Echidna in Sonic the Hedgehog 2 rom
I have changed the romname and the checksum (which needs to be calculated for each area). This will cause the screen to change as follows.
>   [Cart info](https://twitter.com/scrap_a_/status/1439940810292613123?s=20) 
>   [Checksum](https://twitter.com/scrap_a_/status/1439940819851497473?s=20) 
I've abbreviated Sonic & Knuckles to SnK, but if you …
> Add support for Sonic & Knuckles Lock-on games

- Cart_Reader/MD.ino
Fixed bug and comment about Sonic & Knuckles Lock-on games.
> bugfix about Sonic & Knuckles Lock-on games

- Cart_Reader/WS.ino
- Cart_Reader/options.h
Supporting ws adapter v2 for HW4.
Also add more cart info and showing up progress bar when reading ROM
[ws_adapter_v2.zip](https://github.com/sanni/cartreader/files/8146787/ws_adapter_v2.zip)
> Ws adapter v2

- Cart_Reader/GB.ino
Tested with Momotarou Collection 2.
> Support reading game/save using MMM01

- sd/gg.txt
up to date with latest GG no-intro DAT (2022-05-31)
> gg.txt for GameGear

- Cart_Reader/GBA.ino
This adds support for the missing flash chips used for Game Boy Advance save data. Currently only SST 39VF512 and Macronix MX29L010 are supported.
Added for 512K FLASH:
- Atmel AT29LV512
- Macronix MX29L512
- Panasonic MN63F805MNP
Added for 1M FLASH:
- SANYO LE26FV10N1TS
> Add support for missing GBA flash save chips

- Cart_Reader/SNES.ino
Tested with Street Fighter Zero 2 Japanese version.
> Support for dumping "Street Fighter Zero 2" (SDD1 ROM Only)

- Cart_Reader/SMS.ino
- "Retron 3in1" adapter support for GG dumping added
- 32KB GG and SMS carts are now handled same
> "Retron 3in1" support for GG added

- Cart_Reader/NES.ino
confirmed working with Fantasy Zone (J)
> fixed mapper 93

- Cart_Reader/NES.ino
tested working with multiple NES and FC carts using UNROM-512
> fixed mapper 30

- Cart_Reader/NES.ino
added NES mapper 11 (Color Dreams)
tested working with Shockwave
> added NES mapper 11

- Cart_Reader/NES.ino
added NES mapper 62, tested working with a multicart using K-1017P PCB also expanded max PRG size for these big multicarts
> added NES mapper 62

- Cart_Reader/NES.ino
added NES mappers 58 + 200 + 201 + 203 + 213 + 225 + 229 + 232
> added 8 more NES mappers

- Cart_Reader/NES.ino
> added NES mapper 202

- Cart_Reader/NES.ino
> fixed NES mapper 203

- Cart_Reader/NES.ino
> more NES mappers fixes

- Cart_Reader/NES.ino
added NES mappers 240 and 246 and 255
> added NES mappers 240 and 246 and 255

- Cart_Reader/SMS.ino
Use sg1000.txt database to verify/rename SG-1000 dumps
> Use sg1000.txt database

- Cart_Reader/NES.ino
> added NES mapper 36

- Cart_Reader/NES.ino
added NES mapper 91 + m36 typo fix
> added NES mapper 91 + m36 typo fix

- Cart_Reader/NES.ino
fixed NES mapper 206, tested working with FC game "Super Chinese"
> fixed NES mapper 206

- Cart_Reader/NES.ino
> added NES mapper 111

- Cart_Reader/NES.ino
added NES mapper 228 (Action 52 + Cheetahmen II) - NEED TESTING
> added NES mapper 228 - UNTESTED

- Cart_Reader/NES.ino
> fixing NES mapper 228

- Cart_Reader/NES.ino
forgot to set the high bit for bigger carts
> fixed mapper 226

- Cart_Reader/NES.ino
I finally got 2 carts to confirm dumping is working with this fix
> fixed mapper 225/255

- Cart_Reader/NES.ino
added NES mapper 28, tested working with 2x Action 53 cartridges
> added NES mapper 28

- Cart_Reader/NES.ino
added NES mapper 176, tested working
> added NES mapper 176

- Cart_Reader/NES.ino
> addes NES mappers 178+227+241

- Cart_Reader/NES.ino
added NES mappers 42+142+157+162+163+177
> added NES mappers 42+142+157+162+163+177

- Cart_Reader/NES.ino
> added NES mappers 46+52+212

- Cart_Reader/NES.ino
added NES mappers 59+63+113+126+134+174
> added NES mappers 59+63+113+126+134+174

- Cart_Reader/NES.ino
solving mappers with bus conflicts, mapper 2 is fixed, more to come after more testing
> [WIP] solving mappers with bus conflicts

- sd/snes.txt
> Fix wrong crc32 and cart size for Kakinoki Shougi (Japan)

- Cart_Reader/NES.ino
fixed mapper 63, tested working with Powerful 255-in-1 (CH-011 PCB)
> fixed mapper 63

- Cart_Reader/NES.ino
mapper 209 dumps the same as 35, 90 and 211
also added info about unused mappers (20, 84, 100,101, 151, 186 and 248)
> mapper 209 dumps the same as 35, 90 and 211

- Cart_Reader/NES.ino
fixed mapper 23, tested working with Ganbare Goemon 2
> fixed mapper 23

- Cart_Reader/NES.ino
added mapper 31, 57, 214
fixed 94, 97, 180 for bus conflicts
fixed mapper 73 (see discussion https://github.com/sanni/cartreader/discussions/657 about Salamander)
merged 200+212
> added mappers 31, 57, 214 + fixes

- Cart_Reader/NES.ino
> added mappers 56 + 236

- Cart_Reader/VBOY.ino
A progress bar is now displayed during ROM dumping
> Add progress bar

- Cart_Reader/MD.ino
Fixes cart size, rom header provides wrong values
> Add support for Beggar Prince rev.1

- Cart_Reader/NGP.ino
Add support for :
- "16M / 32M Pocket Flash Card" : old flashcarts, respectively in black, and transparent purple cases. Since their flash chips are returning 0x204C value (4Mbits), you will need to manually select the wanted ROM size before dumping them.
- "NeoGeo USB Flash Masta 2 in 1" : contains 2x 16Mbits Fujitsu chips, now detected fine.
> Add some flashcarts dumping support

- Cart_Reader/NES.ino
> fixed mapper 36

- Cart_Reader/WS.ino
Also:
Correct color flag for "BANC1A"
Correct rom dump size of jss2/dknight to match db crc32
> Speed up wonderswan checksum calculation by moving codes into rom dump procedure

- Cart_Reader/GB.ino
Only tested with "Korokoro Kirby (Japan)".
Should resolve #717.
> Add support for reading/writing MBC7 EEPROM

- Cart_Reader/LOOPY.ino
Sorry, I found a bug in the SRAM backup routine that shifted one byte out of place (which is definitely enough to break my saves!)
> Fixes Loopy SRAM dumping

- Cart_Reader/GB.ino
This adds full read and write support for all GB/GBC Pelican Codebreaker, Monster Brain, and Brainboy devices. This is fully tested and working.
> Pelican Codebreaker / Monster Brain / Brainboy Support

- Cart_Reader/GB.ino
This update implements read and write functions for the Datel GBC GameShark and the Datel Mega Memory Card.
> Add GBC GameShark and Mega Memory Read and Write Functions

- README.md
- sd/pce.txt
> Add SuperGrafx entries to SD

- Cart_Reader/2600.ino
Support for the Atari 2600 F4, F6 & F8 variant with RAM at 0x1000-0x10FF - also called FxS (Sara) or FxSC (SuperChip). Dumping those games without SC will cause odd byts depending on the RAM content.
Some dumps circulating have 0x00 some dumps 0xFF at this address. I went for 0xFF.
Known games are:
- Crystal Castles
- Dark Chambers
- Defender II
- Desert Falcon
- Dig Dug
- Fatal Run
- KLAX
- Jr. Pac-Man
- Millipede
- Off the Wall
- Radar Lock
- Save Mary!
- Secret Quest
- Shooting Arcade
- Sprintmaster
- Stargate
- Super Football
I have tested NTSC Jr. Pac-man and PAL Radar Lock
> support for F4SC, F6SC & F8SC

- Cart_Reader/7800.ino
reduces the memory footprint for 7800.ino. My overall memory consumption was down ~1.5%
> reduce memory footprint for 7800.ino

- Cart_Reader/C64.ino
should fix dumping of bankswitch cartridges of C64 with hw5.
Could only test DeathFlood (mapping type 19) at the moment. Because it is my only c64 cartridge requiring bank switching.
> support CLOCKGEN for C64

- Cart_Reader/2600.ino
- Cart_Reader/5200.ino
- Cart_Reader/7800.ino
- Cart_Reader/ARC.ino
- Cart_Reader/C64.ino
- Cart_Reader/COLV.ino
- Cart_Reader/FAIRCHILD.ino
- Cart_Reader/INTV.ino
- Cart_Reader/MSX.ino
- Cart_Reader/NES.ino
- Cart_Reader/ODY2.ino
- Cart_Reader/OSCR.cpp
- Cart_Reader/OSCR.h
- Cart_Reader/VECTREX.ino
- Cart_Reader/WSV.ino
removed some more duplicate code so I could enable more devices in parallel
> remove some duplicate printing code and declare more global text strings

- Cart_Reader/2600.ino
> Add support for mapper 3E, 32K ROM 32K RAM Tigervision

- Cart_Reader/NES.ino
Support fo flash NES - NROM mapper 0 (flash memory A29040B) carts most found on AliExpress >
Also renamed the Flash NESMaker option to Flash Repro and created a sub-menu for flash repro implementations.
> Support NES Flash repro A29040B and menu replacement.

- Cart_Reader/2600.ino
Add support for atari2600 SUPERBank 128-256K mapper, supports Casey's Gold
> Add support for atari2600 SUPERBank

- Cart_Reader/Cart_Reader.ino
2000th commit yo
the best kind of commit: 2024 -> 2025
keep up the good job everyone :D
> Update Cart_Reader.ino - 2024 -> 2025

- Cart_Reader/MD.ino
This adds support for flashing flash carts with CFI 16 bit flash chips.
Currently supports 2x 16MBit board by Bucket Mouse here: https://github.com/MouseBiteLabs/Genesis-Cartridges/tree/main/Advanced%20Flash
I'm planning to add support for a 1x 16MBit board as soon as I build one and others if I can get a prototype.
Based on the existing SNES CFI support.
> Add support for flashing CFI-based flash cart for Genesis

- sd/md.txt
Validated rom dump:
CRC32: 634679bb
MD5: e1ade52f6ddb7bad12c2576d9ac18b14
SHA-1: 4556c9740cecc7c2294ba49cd2a23999a1834275
Notes:
* Dumped multiple times with same hashes
* Tested with emulator to validate that rom functions
* Original product page: https://www.columbuscircle.co.jp/products/?id=1733298301-485446&ca=22
* Amazon link: https://www.amazon.co.jp/dp/B0DQ6XJFWP
> Added Sol-Deace (Japan) (Columbus Circle).md to md.txt

- Cart_Reader/MD.ino
The 29F800 supports CFI commands as-is except for the ID command, so this adds custom code to identify it.
Rewrote the identifyCFI function a bit to make it more readable.
> Add support for Genesis 29F800 under CFI.
