sanni/cartreader

Cart_Reader/Cart_Reader.ino
Visual Micro is an extension for Visual Studio, a much more capable IDE than regular Arduino.
As part of the build process it combines all .ino files into one large file.
When building the file, some #includes need to be the first code it sees, else the step fails.
This is the minimum amount of change that makes it work.
It'd be great to have it ;p
=> small change that allows using Visual Micro instead of the Arduino IDE

Cart_Reader/Cart_Reader.ino, Cart_Reader/FLASH.ino, Cart_Reader/GB.ino, Cart_Reader/GBA.ino, Cart_Reader/MD.ino, Cart_Reader/N64.ino, Cart_Reader/NP.ino, Cart_Reader/PCE.ino, Cart_Reader/SNES.ino, Cart_Reader/SV.ino
replace the assembler jmp 0 reset method with resetArduino() that uses the watchdog timer to reset the device. This is the preferred method, as it initializes the device more correctly.
=> arduino_reset

Cart_Reader/Cart_Reader.ino, Cart_Reader/FLASH.ino, Cart_Reader/GB.ino, Cart_Reader/GBA.ino, Cart_Reader/MD.ino, Cart_Reader/N64.ino, Cart_Reader/NP.ino, Cart_Reader/PCE.ino, Cart_Reader/SNES.ino, Cart_Reader/SV.ino
conserve ~ 800 byte SRAM by putting menu strings in progmem. 
Free bytes now: ~ 4000
I reduced one dynamic string that combines a crc with a question_box title to just the static title.
The crc is shown before that though, so I figure it's fine.
This is a large change but sram is precious. 
Future question_box titles will be progmem strings only as well.
=> strings_to_flash

Cart_Reader/Cart_Reader.ino, Cart_Reader/GB.ino, Cart_Reader/GBA.ino, Cart_Reader/N64.ino, Cart_Reader/PCE.ino, Cart_Reader/SNES.ino
roughly double n64 dumping performance by using the 1024 byte file buffer and combining the checksum and dumping code; also some cleanup
The dumper routine can probably do the crc32 calculations instead of the 310ns NOP delay.
For that I'd first like to check the timings with a logic analyzer first though.
But the crc32 code is surely longer than 310ns, I think :)
=> n64_speedup

Cart_Reader/MD.ino, Cart_Reader/N64.ino, Cart_Reader/SNES.ino
I've only checked and dealt with SNES, MD and N64.
It'd be nice to avoid writing all kinds of bad files to SD card, so that users can be confident that everything that IS on a card is also valid.
=> SNES, MD: avoid dumping/writing 0 Byte files to SD card

Cart_Reader/Cart_Reader.ino, Cart_Reader/MD.ino, Cart_Reader/NES.ino, Cart_Reader/SNES.ino
There were three global variables used in both MD.ino and NES.ino:
* int index  -> changed to use local variables
* byte eepbit[8];  byte eeptemp;   -> moved to Cart_Reader.ino
Other changes:
* add #ifdef enable_NP around call to setup_SFM  (in SNES.ino)
* add #ifdef enable_MD around call to mdCartMenu (in Cart_Reader.ino)
=> modular compilation fixes

Cart_Reader/NP.ino, Cart_Reader/SNES.ino, Cart_Reader/snes_clk.cpp, Cart_Reader/snes_clk.h
This adds a check for a file named "snes_clk.txt" in the root of the SD card and loads the clock offset from it (16 characters max for the offset).  This will allow people to keep a file on there with the offset they need for their particular clock generator and not have to worry about editing the sketches each time a new version comes out.
=> Load SNES clock generator offset from SD card

Cart_Reader/NES.ino
This will make it easier for people to tell whether an NES ROM had a header successfully prepended to it without having to catch the message on the cart reader when that happens, look at the ROM in a hex editor, or load it up in an emulator.
=> Output unheadered NES ROMs as CART.bin

Cart_Reader/NES.ino
I realized that I was getting different CRC32 values for complete NES ROMs (PRG + CHR) than I expected, and it turns out I missed skipping the header when calculating the CRC for a headered ROM.  This fixes that.
=> Corrected miscalculated CRC32 for headered NES ROMs

Cart_Reader/SMS.ino
I tried to dump The Pro Yakyuu '91 (Game Gear), this game is 128KB (1Mbit), but the nibble of 0x7FFF is 0x3. I found this by temporarily setting the default to 128KB and successfully dumping it.
I couldn't find any other information about titles that use 0x3, but this value seems to be correct for this title (consistent with the No-Intro database).
=> SMS: add a strange checksum from The Pro Yakyuu '91 (Game Gear).

Cart_Reader/N64.ino
This has been confirmed to allow dumping v1.07, v1.09, v2.0-2.21, v3.2-3.3 with the below flash memory chips. Versions not listed may not work correctly or even be supported.
SST 29LE010
SST 28LF040
AMTEL AT29LV010A
SST 29EE010
=> GameShark Dump Compatability Update

Cart_Reader/GB.ino, Cart_Reader/NES.ino, Cart_Reader/PCE.ino, Cart_Reader/SMS.ino, Cart_Reader/snes_clk.cpp
I noticed a number of build warnings in the code (including some overflow warnings in the SMS module; I guess the default number representation is small enough that 32768 doesn't fit in the allocation), so this should resolve them.
=> Fixed build warnings

Cart_Reader/NES.ino
- worked with one of the PCB manufacturers to fix the flash reset code (lines 4015/4030)
- per the INL code spec skipped the first 16 bytes as they're header information:  https://gitlab.com/InfiniteNesLives/INL-retro-progdump/-/blob/master/host/scripts/nes/mapper30v2.lua#L549
test flashed multiple pcbs and roms, confirmed works
=> fix flashing of unrom-512 boards

Cart_Reader/SMS.ino
32KB GG carts don't use mapper.
Games sush as Columns, Woody Pop etc. are now dumped fine.
=> Fix 32KB GG

Cart_Reader/Cart_Reader.ino
I was trying to automate the build process using github actions and arduino-cli but the Arduino-RGB-Tools library caused problems: ``Library install failed: library not valid``. 
Since the library is not available in the Arduino Library Manager it is  considered "unsafe" (since it has not passed through the [Library Manager submission process](https://blog.arduino.cc/2021/06/07/new-workflow-for-arduino-library-submissions/)) and it is more complicated to install in an automated fashion. 
In my optinion the library doesn't offer a lot of functionality and it can be replaced by just a few analogWrite calls which are provided by Arduino already. After removing the Arduino-RGB-Tools library, all required libraries can be installed via the Arduino Library Manager.
I only have version HW5 …
=> Remove Arduino-RGB-Tools lib, use analogWrite instead

.github/workflows/build.yml, .github/workflows/ci.yml
This PR adds a github workflow which enables building the project on github on each push.
To build the project, ``arduino-cli`` is used (on an Ubuntu runner). It should give the same result as compiling the project using the portable IDE shipped with each release. All the required libraries are included using ``arduino-cli lib install``. The code is compiled separately for each hardware revision.
Having a central builder can help finding problems before merging.
Currently the code is only build and the only outcome is to see if the code compiles. In the future, maybe binaries can be build automatically for releases, so that users can directly download a binary file of the firmware and flash it so you don't need to compile the code yourself and you don't need windows to compile.
To …
=> Add github actions workflow to build code for each HW rev. on each push

Cart_Reader/GB.ino, Cart_Reader/GBA.ino
Displays better names for Game Boy games, e.g. `KIRBYSP` will now show up as `KIRBY'S PINBALL`. Non-printable characters and those not valid for filenames (`<>:"/\|?*`) are replaced by underscores, null characters are still skipped.
For Game Boy, names of mappers `MBC7`, `HuC-1` and `HuC-3` will also be displayed as these are currently supported at least for ROM reading.
=> Display full ROM title for GB and GBA and more mapper names for GB

Cart_Reader/GB.ino
Should make reading the ROM data of the following cartridges possible:
- DMG-602 CHN / Mani 4 in 1 - Bubble Bobble + Elevator Action + Chase H.Q. + Sagaia (China) (En)
- DMG-603 CHN / Mani 4 in 1 - Genki Bakuhatsu Gambaruger + Zettai Muteki Raijin-Oh + Zoids Densetsu + Miracle Adventure of Esparks - Ushinawareta Seiseki Perivron (China) (Ja)
- DMG-604 CHN / Mani 4 in 1 - R-Type II + Saigo no Nindou + Ganso!! Yancha Maru + Shisenshou - Match-Mania (China) (Ja)
- DMG-605 CHN / Mani 4 in 1 - Takahashi Meijin no Bouken-jima II + GB Genjin + Bomber Boy + Milon no Meikyuu Kumikyoku (China) (Ja)
=> Use correct mapper type for GB Mani 4 in 1

Cart_Reader/NES.ino
added NES mapper 79: NINA-03 and NINA-06 circuit boards, produced by American Video Entertainment. tested working with Deathbots and Dudes with Attitude
=> added NES mapper 79

Cart_Reader/NES.ino
added mapper 146 (Sachen 3015 PCB for Famicom)
not tested but identical to mapper 79 according to https://www.nesdev.org/wiki/NINA-003-006
=> added mapper 146

Cart_Reader/NES.ino
added NES mapper 15, tested working with 2 carts using a K-1030P PCB
=> added NES mapper 15

Cart_Reader/NES.ino
Added NES mapper 235, tested working with Golden Game 260-in-1 (GS-2018 PCB)
Added support for 4MB PRG (needed for these kind of carts)
=> Added NES mapper 235

Cart_Reader/NES.ino
added NES mapper 242, tested working with "1992" 190-in-1 multicart (ET-113 PCB), both on FC and NES
=> added NES mapper 242

Cart_Reader/NES.ino
Added NES mapper 60 for reset-based NROM-128 4-in-1 multicarts. Tested working on 7 different NES carts.
=> Added NES mapper 60

Cart_Reader/SNES.ino
The header offsets were wrong so the size wasn't correctly computed and generally ended up defaulting to 32KB. Stunt Race FX, at least, uses 64KB and so only half the save data was being read.
=> fix superfx sram size detection

Cart_Reader/SFM.ino
Please check this diff, as this cleanup is not as clear-cut as the previous ones.
These variables are set but never read. Removing them removes a non-trivial amount of code, which I am not comfortable deleting: it contains knowledge about cart data structure, even though it is currently not being used for anything. So comment it out until someone who know this architecture better comes around.
Frees 146 bytes of program space and 16 bytes of global ram space.
=> SFM.ino: Get rid of write-only global variables

Cart_Reader/COLV.ino, Cart_Reader/Cart_Reader.ino, Cart_Reader/FLASH.ino, Cart_Reader/GB.ino, Cart_Reader/GBA.ino, Cart_Reader/GBM.ino, Cart_Reader/GBS.ino, Cart_Reader/INTV.ino, Cart_Reader/MD.ino, Cart_Reader/N64.ino, Cart_Reader/NES.ino, Cart_Reader/NGP.ino, Cart_Reader/PCE.ino, Cart_Reader/PCW.ino, Cart_Reader/SFM.ino, Cart_Reader/SMS.ino, Cart_Reader/SNES.ino, Cart_Reader/SV.ino, Cart_Reader/VBOY.ino, Cart_Reader/WS.ino, Cart_Reader/WSV.ino
The N64 code was heavily modified, going from 3 sets of functions handling the JoyBus in the source code (2 in any build) to a single one (both in source and in binaries). The low-level JoyBus functions are now in assembler, which frees enough time to pack received bitstream into bytes instead of having to do so as a second step after the transfer. Also, convert sequences of NOPs into a delay loop, for better program space efficiency.
Overall, this patch set shrinks the HW3 build by 4.4kB of program space and just shy of 400B of global ram space. The amount of space saved should be comparable on other hardware revisions.
=> More resource usage reduction efforts: factorise N64 JoyBus code, print_Error split

Cart_Reader/SFM.ino, Cart_Reader/SNES.ino
Similar to the parts of cc17c70e304fb106b0399b333f86fcc68d70dc32 which touch SFM.ino and SNES.ino . Plus another hunk that I am not sure was correct to discard.
=> Re-fix compiler warnings

.github/workflows/ci.yml, Cart_Reader/Cart_Reader.ino, Cart_Reader/NES.ino
Fixing a warning and enabling warning reporting during CI. I recommend setting the arduino IDE to "Warnings: All" level to catch these during development.
Commenting `rewind_line` because its implementation is not immediately obvious.
Moving `EEPROM_`{`read`,`write`}`Anything` in preparation for some more work, changing the exact order in which the arduino build system composes the final monolithic c++ source file before compilation.
=> Assorted small changes

Cart_Reader/NES.ino
added NES mapper 226, tested working with NES pirate multicart 42-in-1
=> added NES mapper 226

Cart_Reader/MD.ino
Fixed a problem that lock-on games in "Sonic & Knuckles" is not recognized. Apparently, the compiler's behavior for variable initialization has changed.
- Added initialization of char variable.
- Fixed the judgment method of string comparison.
- Updated checksum text and position.
=> Fix Sonic & Knuckles

Cart_Reader/NES.ino
adjusting min/max sizes for some mappers, this is required to dump some recent carts: Lucky Penguin is 64k mapper 2
Project Blue is 512k mapper 34
=> adjusting min/max sizes for some mappers

Cart_Reader/SFM.ino, Cart_Reader/SNES.ino, sd/snes.txt
Fix for "Kakinoki Shougi (Japan)"
Doing compareCRC when reading game from SFM.
Don't rename when doing checksum, just use filename and folder.
=> Fix SNES "Kakinoki Shougi (Japan)"

sd/n64.txt
CRC1 match for the two cartridges, causing the first one encountered to be chosen even when it's the wrong size.
=> Fix F-Zero X being detected as F-Zero X Beta

Cart_Reader/Cart_Reader.ino, Cart_Reader/SUPRACAN.ino
Add support for dumping Super A'can game and save.
Adapter PCB gerber file is attached. PCB thickness is 1.2mm.
For building your own Super A'can cartridge slot, go #354 for more detail.
[SuperAcanAdapter.zip](https://github.com/sanni/cartreader/files/10810685/SuperAcanAdapter.zip)
=> Add support for dumping Super A'can game and save

Cart_Reader/PCE.ino, sd/pce.txt
Chip is 1MB, app data only on 512kB.
=> Add support for Dinoforce (World)

Cart_Reader/GBA.ino
Building the Game Boy Advance ROM name was fixed; it was short by one character.
Game Boy Advance cartridges with 32 MB of ROM and an EEPROM save type use the final 256 bytes in ROM space for EEPROM access (see [GBATEK: GBA Cart Backup EEPROM](https://problemkaputt.de/gbatek-gba-cart-backup-eeprom.htm)). This fix will restore the original padding data.
=> GBA: Fixes ROM name length and reading 32 MB carts that use EEPROM saves

Cart_Reader/SNES.ino
Sound Novel Tsukuru on my unit would not dump properly, with only the first two MB correctly dumped, and the last MB filled with FF bytes. After some digging, I found that there was a similar issue for Derby Stallion '96 with the same symptoms (both are carts with a slot for a Satellaview memory pack). I tried using its fix for Sound Novel Tsukuru, and was able to get a verified dump.
Relevant links:
https://github.com/sanni/cartreader/discussions/760#discussioncomment-5552247
https://github.com/sanni/cartreader/issues/799
=> SNES.ino: Fix dumping Sound Novel Tsukuru (Japan)

Cart_Reader/C64.ino
With my hw5  I have an issue dumping C64 carts with mappings of 6 or higher resulting in message "crc 0x0000000" with an empty file on sd card. I think the controller has an issue with declaring a variable inside the case statement but without its own scope. Afaik this should be solved by the compiler or result into an error at compiler stage. With the additional scoping the code works fine for me.
=> fix reading mapping > 5 causes crc 0x0000000

Cart_Reader/MD.ino, sd/md.txt
Slaughter Sport has its header in the wrong location, causing the ID to be read as the title, resulting in a folder called 'GMT5604600jJ' - the offset read as the ID is hex that can't be displayed as a string. The offset containing the checksum is also FF FF.
This corrects the title and therefore the folder name to match what is in the header (albeit the wrong offset), as well as the checksum. It also corrects the CRC32 in the txt file which currently points to a trimmed version. I placed it right after the title is read as the other code using romName runs after the title has been properly read, rather than correcting it, so it seemed that corrections should be at the top. If others are found this could be a "//misplaced headers check" section rather than just Slaughter Sport.
ESPN …
=> Fix Slaughter Sport title, two CRC32s

Cart_Reader/COLV.ino, Cart_Reader/Cart_Reader.ino, Cart_Reader/Config.h, Cart_Reader/INTV.ino, Cart_Reader/NES.ino, Cart_Reader/WSV.ino
* moved the GB code to Cart_Reader.ino
* replaced the nearly identical functions in WSV, COLV and INTV
* little change of function to only read one letter (instead of reading 100-128 bytes fix than moving backwards) couldn't see any significant speed changes - but keeps the functions memory footprint smaller
Some remarks:
* getline "maxi" parameter seems odd. It reads number - 1. Thus 2 has to be passed to read one byte. I think this is not max but buffer size. The parameter name is irritating.
* It would be nice to change the code to stop if a letter >= is found. So for example if COLV _X_ is searched it stops at _Yolk's on you, The (Europe) (Proto).col_. But currently NES first entry should be placed at the end of the file due to "[" > "Z" if this is changed, it would require a modified …
=> remove duplicate code of seeking database files for letters

Cart_Reader/7800.ino, Cart_Reader/COLV.ino, Cart_Reader/Cart_Reader.ino, Cart_Reader/Config.h, Cart_Reader/INTV.ino, Cart_Reader/NES.ino, Cart_Reader/WSV.ino, sd/7800.txt
please review https://github.com/sanni/cartreader/pull/934 first. This one extends on this change.
This pull requests replaces the cart selection code of 7800 with the afaik more user friendly code of NES, COLV, INTV & WSV. Plus due to the code similarities the used space of the program is reduced in my configuration from
243718 to 242794 Bytes
Downside the cart database structure for the 7800 must be changed. If some user only update the firmware without the SD card - cart selection does not work until SD card is updated.
If this is ok - I would like to change 2600 and C64 as well.
=> replace cart selection code of A7800 with one used at NES, COLV, INTV, WSV

Cart_Reader/Config.h, Cart_Reader/OSCR.h, Cart_Reader/PCE.ino, Cart_Reader/SFM.ino
Adds support for reproduction HuCards that use SST39SF010, SST39SF020, SST39SF040, MX29F040, or MX29F080 flash chips. One such open-source design is by Ichigo: https://github.com/partlyhuman/HuCARD-repro. There may be others out there — I have only tested this with the linked one but would be willing to extend support to others as requested.
This can be disabled to save program space by removing flash repro support (`#undef ENABLE_FLASH`). Made every attempt to minimize additional program size (maximized string reuse).
Additionally, includes a fix for broken compilation when building SFC/SNES support without flash support.
Comments welcome.
https://github.com/sanni/cartreader/assets/327136/03192727-4a6f-49c4-8fd7-41e2f096d8de
=> Adds support for flashing reproduction HuCards

Cart_Reader/NES.ino
Here's my fix for reading VRC2B Famicom Carts (Mapper 23) on HW5.  The symptoms were reading incorrect CHR data on VRC2B carts resulting in consistently bad dumps with the wrong CRC32.  If you think there is a better way to fix the issue, please feel free to reject.  I know that this fixes the specific issue for myself with minimal risk of impacting other mapper types.
Example log with a bad dump of Contra (J):
```
Saving to NES/ROM/Contra/481/...
[*******************]
CRC32... 6F0B8DB7 -> Not found
```
Instead of bank switching on a single bank and reading 1024 bytes at a time, this update switches 8 banks at a time and reads 8 KiB per iteration. The hypothesis is that the timing between bank switching and reading 1024 bytes at a time is insufficient for the mapper while reading in …
=> Fix for VRC2B Famicom Carts

Cart_Reader/SMS.ino
1. SMS cart size detection algorithm is updated based on bank count instead of multiples of detected cart size from the header.
2. SMS cart size detection is only invoked if the "TMR SEGA" header is parsed for non-JP carts.
3. Manual selection of ROM size is now present in the SMS/GG menus to allow for manual override as detection algorithm does not work correctly for Cloud Master and Penguin Land US SMS carts.
4. SG-1000 Operation menu now allows for reset instead of relying on a power cycle.
Notes:
I think a better long-term solution is to implement a CRC on the first 8 KiB + database lookup for SMS/GG/SG-1000 to determine the correct ROM size (or something similar to how NES/Famicom auto mapper detection works).  This is especially true as not all carts have the "TMR SEGA" header …
=> SMS Updates

Cart_Reader/5200.ino, Cart_Reader/Cart_Reader.ino, sd/5200.txt
1. Added CRC database lookup for ROM dump validation and file renaming
2. Added delays to improve successful ROM dumping. Especially helps with 2-chip ROMs
3. Fixed database mapper config for Star Trek (not a 2-chip ROM)
Tested with multiple carts with HW5:
Vanguard (2-chip)
```
OSCR HW5 V14.0
[+] PC Engine/TG16
[+] Atari 5200
ATARI 5200 READER
CURRENT SETTINGS
MAPPER:   1
TWO CHIP
ROM Size: 16K
[+] Select Cart
Select Mapping from List
ATARI 5200 READER
CURRENT SETTINGS
MAPPER:   0
STANDARD
ROM Size: 32K
[+] Read ROM
Saving to 5200/ROM/ATARI/751/...
CRC32... CAAEA0A4 -> Vanguard (USA).a52
```
Jungle Hunt (2-chip):
```
OSCR HW5 V14.0
[+] PC Engine/TG16
[+] Atari 5200
ATARI 5200 READER
CURRENT SETTINGS
MAPPER:   0
STANDARD
ROM Size: 16K
[+] Select Cart
Select Mapping from List
ATARI 5200 …
```
=> Atari 5200 Updates

Cart_Reader/LOOPY.ino, Cart_Reader/LYNX.ino
Tested with [this 512KB Lynx flash cartridge from K-Retro](https://k-retro.com/atari-lynx-flashsd-carts/43-512k-flash-128b-eeprom-flash-cartridge-for-atari-lynx.html)
Written to support .lnx files with and without a header — i saw both variants when looking at existing sets.
Easy enough to expand to more chips, if there are other Lynx flash carts out there. Let me know if you know of any.
=> Adds flash cartridge support to Atari Lynx firmware

Cart_Reader/GBM.ino
These are just some changes in comments and in one unused function. It has no effect, but I would like to submit this for documentation purposes.
I played around with the NP GB Memory cartridge on a different hardware and your code helped me to be able to fully read and write the cartridge. But I figured out by testing that some of the comments are not correct. Especially the GBM command 0x05 does NOT map the menu. It re-enables the mapping that was selected previously. So, if the menu was selected before disabling the mapping with the 0x04 command, then the menu mapping will be re-enabled again when sending the 0x05 command. But if some other mapping was selected before (like with 0xC1, 0xC2, ...), then that particular mapping will be re-enabled by 0x05.
I don't know if this behavior …
=> GBM: Fix some comments and unused function

Cart_Reader/LYNX.ino
Thanks to @PsyK0p4T for discovering this issue with some runs of Electrocop. I've seen it dumped at two sizes, but one is an overdump. Apparently some carts are produced on maskroms bigger than needed, and we should expect empty areas to be initialized to 0s instead of 1s with NOR flash.
=> Fix for overdumping Electrocop/Lynx

Cart_Reader/Cart_Reader.ino
- Removed a global variable that's only used by SERIAL_MONITOR that was better used as a local temporary variable (`incomingByte`). The local variables are also better typed to be either `byte` or `char` (I chose `char`s due to the next point).
- Simplified `Serial.read()` cases to extract the character read as a char and not the subtraction of the character with 48. This reduced code size slightly.
- The actual change that made me make this PR: I tried running the SNES clock calibration using SERIAL_MONITOR, but it wasn't able to trigger saving to the SD card because the `checkButton` implementation for SERIAL_MONITOR did not return `4`, or long press. I've implemented to return that value if the user sends `'l'` or `'L'`.
-  Got rid of a large comment block in one of the SERIAL_MONITOR …
=> Cleanups for SERIAL_MONITOR interface, and support "long press" with SERIAL_MONITOR

Cart_Reader/NES.ino
This is minor issue fix on NES PRG dump in mapper 24, 26 and 78.
For switchable PRG rom bank, it's required to read $8000-$BFFF (16kb). But it has read $A000-$BFFF, since the offset address is wrong. Thus, dumped PRG file is as half size as expected.
I've confirmed the code works in the following titles:
- Akumajou Densetsu (mapper 24)
- Esper Dream 2 - Aratanaru Tatakai (mapper 26)
- Mouryou Senki Madara (mapper 26)
- Uchuusen Cosmo Carrier (mapper 78)
=> Fix NES PRG address for mapper 24/26/78

sd/snes.txt
Added the database entry for SNES/SFC for Cotton 100% JPN (Columbus Circle Release).
This cart is an official aftermarket re-release of the original cart (https://www.amazon.co.jp/dp/B0C6SL86QG).
There are minor differences in the ROM dump for the credits to reflect the updated 2023 copyright.  While the read header checksum remains the same for the initial database lookup, the calculated checksum differs.  This means that the internal checksum check is expected to fail without a hack in the [`checkAltConf()` function in SNES.io](https://github.com/sanni/cartreader/blob/master/Cart_Reader/SNES.ino#L1057-L1150). However, the card dumps correctly and the final checksum results in the correct filename resolution from the database.
Log snippet:
```
SCR HW5 V14.5
[+] Super Nintendo/SFCSuper …
```
=> Added SNES/SFC database entry for Cotton 100% (Columbus Circle Release)

Cart_Reader/MD.ino
This change detects when the serial number of the second flash chip matches the
first one, indicating that the flash cart only has one chip.
I also added some F() calls that I forgot in my previous change.
=> Detect one chip boards for Genesis CFI repro flash carts.

Cart_Reader/MD.ino
The code in master gets compilation errors when trying to build without ENABLE_MD defined.
```
Arduino: 1.8.19 (Windows 10), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"
D:\Develop\cartreader_V15.0_Portable\Arduino IDE\portable\sketchbook\Cart_Reader\MD.ino: In function 'void eraseFlashCFI_MD()':
MD:3046:38: error: 'totalChipsCFI' was not declared in this scope
3046 |   for (byte currChip = 0; currChip < totalChipsCFI; currChip++) {
|                                      ^~~~~~~~~~~~~
D:\Develop\cartreader_V15.0_Portable\Arduino IDE\portable\sketchbook\Cart_Reader\MD.ino: In function 'void eraseFlashCFIChip_MD(byte)':
MD:3059:3: error: 'dataOut_MD' was not declared in this scope; did you mean 'dataOut16'?
3059 |   dataOut_MD();
|   ^~~~~~~~~~
|   dataOut16
MD:3063:3: error: …
```
=> fix build if ENABLE_MD is not defined
